name: Scraper Panamá

on:
  schedule:
    - cron: "0 */2 * * *"   # cada 2 horas (UTC → en Guatemala será 18:00, 20:00, 22:00, …)
  workflow_dispatch:         # permite correrlo manualmente desde Actions

permissions:
  contents: write   # permiso para escribir en el repo

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas selenium
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Run scraper
      run: python scraper.py

    - name: Commit and push results
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add generacion_panama.csv
        git commit -m "Update data $(date)" || echo "No changes"
        git pull --rebase origin main   # 👈 evita conflictos si editaste el repo
        git push
